sonar.projectKey=ansible-community_awx-tui
sonar.organization=ansible-community
sonar.projectName=awx-tui

sonar.sources=awx_tui
sonar.tests=tests
sonar.python.version=3.12,3.13,3.14

sonar.python.coverage.reportPaths=coverage.xml

sonar.newCode.referenceBranch=devel

sonar.exclusions=tests/**,.tox/**,.venv/**,build/**,dist/**
